### ISSUE TITLE
[Probably not an issue] Autoclicker broken ? Nope.

### ISSUE THREAD

**Issue by Harest** [wchill/steamSummerMinigame#100]
Accidentally, i erased my local .js with my options. The actual script seems to not work properly regarding the autoclicker, am i the only one ? Did Valve change something about that ?
// version 3.8.1  

Edit : Okay well, [check this comment](https://github.com/wchill/steamSummerMinigame/issues/100#issuecomment-111851130). *One click to rule them all o/.*

**Comment by strivingsun** [comment]
It does, you just don't see the clicks anymore to reduce lag and the memory leak.

**Comment by Harest** [comment]
If i display text, i see it for my own clicks but not the ones of the autoclicker. I don't think it's normal.
And when i check [the datas over here](https://lab.xpaw.me/towerattack.php), the number of clicks / person is extremely low compared to yesterday.

**Comment by strivingsun** [comment]
It condenses the clicks down so it clicks 1 and is read by the server 20 times. 

I believe that is what wchill said yesterday.

Not sure what to make of the click data, I didn't really believe any of them yesterday because they were all over the board. Some in the quadrillions+ and some in the billions.

**Comment by Limyc-** [comment]
Yeah, something isn't working correctly. I'm not getting any click gold, and lane switching does not seem to be functioning properly (yes, I have auto-fire cannon).

**Comment by strivingsun** [comment]
From: MY AUTOCLICKER IS BROKEN!

"No it isn't. This is because the script is using the newer click method and it only has to "click" once per second (but it counts 20 times). 

Your crits, money, damage, etc. will all appear once per second, and they represent the whole second. (So all Raining Gold money in one second will appear at one time.)"

-wchill

**Comment by strivingsun** [comment]
You might be right about the lane switching because mine isn't working, although it's possible that the lag is just too much and it's not able to switch.

**Comment by NickSC** [comment]
I don't think it is working, because I am getting a very small amount of gold from bosses when they are staying alive for 5+ seconds. If I manually click, I got a billion (server side)

**Comment by Harest** [comment]
I was able to see it more clearly on a boss. Seems like it's working properly indeed. And it's switching lanes.  

Anyway, kudos to the devs ;).

**Comment by Limyc-** [comment]
Just tried using the script on Chrome with TamperMonkey and it worked fine. Firefox with GreaseMonkey does not like the script for whatever reason.

**Comment by Thiana** [comment]
I'm not seeing the click damage text but the autofire damage text is showing. I'm also using Firefox, so I'm guessing something in the overnight changes isnt supported by greasemonkey?

**Comment by Thiana** [comment]
And lane changing is definitely broken too.

**Comment by aaronpburke** [comment]
Chrome (v43.0.2357.124 m) with Tampermonkey (v3.11) doesn't seem to autoclick as of version 3.8.3. It's almost hard to tell on spawners because they die so quickly in my current room, but I can spam-click manually on bosses and farm several hundred million gold. If I do nothing, my gold increases in-line with my auto cannon but nothing else. 

All other features appear to work as intended.

**Comment by wchill** [comment]
I can definitely say that autoclick is still working. If you see a blue number at all, it is working.

**Comment by wchill** [comment]
Lane changing is working for me, so I will need more information (browser, environment, are you on latest version?)

**Comment by Thiana** [comment]
Waterfox 38.0 with Greasemonkey 3.2 on Windows 8. Script version is 2.8.3

**Comment by aaronpburke** [comment]
(My lane-switching is working, since this thread seems to be about two different features not working, but possibly for a related reason.)
I see blue text, but if auto-clicking is working, gold harvested from it while a Raining Gold power-up is active is not adding to my bank (though it doesn't make sense for those to be disconnected).

I can provide any kind of logs/debugging info.

**Comment by Harest** [comment]
Are you sure the gold collected isn't added to your "bank" afterwards ? It can take a few seconds before you see it in your total. For me at least, lvl 1541 and counting, it's working as intended. It was just quite confusing at the beginning because mobs were dying so fast i was seeing 1 level / 20 almost.

**Comment by aaronpburke** [comment]
@Harest You might be correct; Level 1073 and counting, though now that I'm watching it people are nuking bosses -- I am seeing several million added to the bank a few seconds after the boss dies. 

It didn't occur to me that the client-side gold update of the old-style autoclicker might be a usability optimisation that syncs with the server on a different interval.

**Comment by Yves-Be** [comment]
No blue text in Firefox 39, and I've only seen lane switching work a couple of times.
I also see this error in the javascript console: TypeError: this.m_rgLaneData[this.m_rgPlayerData.current_lane] is undefined

**Comment by wchill** [comment]
@Yves-Be: are you using Tamper/Greasemonkey?

**Comment by aaronpburke** [comment]
Okay, now that I've encountered a boss that lived for more than two seconds, I can confirm my autoclicking report can be disregarded. My gold is increasing at rates I would expect. It was simply a visual disconnect of my human brain.

**Comment by Yves-Be** [comment]
I use Greasemonkey

**Comment by alvin853** [comment]
Lane switching not working in Greasemonkey confirmed: 
TypeError: this.m_rgLaneData[this.m_rgPlayerData.current_lane] is undefined running.js:1113:0
TypeError: this.m_data is undefined enemies.js:126:1

**Comment by wchill** [comment]
Try copy paste and see if that works. I have a good idea of why it's broken in Greasemonkey.

**Comment by Yves-Be** [comment]
Copy paste seems to work.

**Comment by Thiana** [comment]
Copy paste what exactly?

**Comment by Limyc-** [comment]
@Thiana Use the manual instructions. Copy/paste the whole script into your browsers console and hit Enter.

**Comment by Thiana** [comment]
With the cut+paste method both click damage and lane changing are working.

**Comment by jamesssun** [comment]
I was copy/paste in Chrome, and it wrote me:

"undefined
VM194:1019 Locking to element 1 as chosen by SteamID
VM194:159 Uncaught TypeError: Cannot set property 'innerHTML' of null"

That's ok?

**Comment by wchill** [comment]
@jamesssun: refresh before you copy paste.

**Comment by jamesssun** [comment]
I/m sorry, but how?

**Comment by alvin853** [comment]
Turn off the Tampermonkey-Script, then Refresh, then copy&paste raw script, otherwise script is running twice

**Comment by jamesssun** [comment]
Sorry for this question. Is that mean, if i'm install script in Tampermonkey, i don't need to copy/paste, it's wroks already?

**Comment by kr0hmy** [comment]
Same issue on Firefox 38.0.5 Mac OS X 10.10.3 Using GreaseMonkey. 
No visible error in console exept : 
TypeError: this.m_rgLaneData[this.m_rgPlayerData.current_lane] is undefined1 running.js:1113:0

But this error is visible even when not using the script, so it doesn't seems related.
Copy paste script works fine !

**Comment by brendanvos** [comment]
This issue is due to be closed, no?

**Comment by wchill** [comment]
Yep
