### ISSUE TITLE
Why is the clickrate set to 20? Is there a server limitation or something?

### ISSUE THREAD

**Issue by perezdev** [wchill/steamSummerMinigame#102]
20 seems really low. And will something happen if we set it higher?

**Comment by strivingsun** [comment]
Yes, if it goes higher the server doesn't register any more than 20 and sometimes not even that.

I think they were going to put in something to randomize the clicks because running 20 cps doesn't get you your max cps that register on the server. They might have already done so.

**Comment by Harest** [comment]
I think the server limit is a little above 20, like 25 but i didn't test effectively. I just know at 30 your money is refreshed (i had a little more displayed before the refresh than you currently have on the server).

**Comment by wchill** [comment]
Server clickrate is supposedly capped at 10, but I have left it at 20. 30 is the absolute highest it will possibly go, and I'm not sure if 30 still works.
