### ISSUE TITLE
[SUGGESTION] Show the version number of the script somewhere on the screen.

### ISSUE THREAD

**Issue by z3ntu** [wchill/steamSummerMinigame#105]
That we see if the script was really updated! And there is a typo in the README.md (Tapermonkey should be Tampermonkey)

**Comment by wchill** [comment]
Too bad there's not a clean way to do this. I have to update version number in both the metadata and a variable. If anyone knows how I can do this in a better way, please advise.

**Comment by z3ntu** [comment]
Ok :) But thanks for the answer!

**Comment by wchill** [comment]
I'll go ahead and make this change, but not immediately

**Comment by ljani** [comment]
[`GM_info().script.version`](http://wiki.greasespot.net/GM_info).

**Comment by wchill** [comment]
^ This does not work if not using Greasemonkey. That's the issue.

**Comment by ljani** [comment]
Oh, you mean for the manual install? Right, I forgot about that.

If dev happens to google this page, the same api is available for [Tampermonkey](https://tampermonkey.net/documentation.php?ext=dhdg#GM_info) as well.

**Comment by Huntakillaz** [comment]
Probably at the bottom of the black options box, something like:
"Script By wchill, version v3.x.x (last updated @ XXmins ago)"

**Comment by brendanvos** [comment]
This issue is due to be closed, no?

**Comment by Septarius** [comment]
Probably, I PR'd the fix based on a chat question but didn't notice this issue before hand. It should have been closed when #119 was merged IMHO.
