### ISSUE TITLE
 wchill -- Merge the fix for crit before you bump the version number !

### ISSUE THREAD

**Issue by Selene29** [wchill/steamSummerMinigame#107]

**Comment by wchill** [comment]
Um, I did?

**Comment by Bo98** [comment]
Shows as you just closed it from here, don't see any commits pushed either.

**Comment by cexikitin** [comment]
Your last commit before bumping the version, is another commit that bumps the version.

**Comment by Selene29** [comment]
you didn't

**Comment by wchill** [comment]
Yeah, just noticed. I'm super tired. Fixed.
