### ISSUE TITLE
Access-Control-Allow-Origin/CORS error

### ISSUE THREAD

**Issue by Septarius** [wchill/steamSummerMinigame#108]
Platform: Chrome Version 45.0.2427.7 dev-m (64-bit)

I get this XMLHttpRequest error sporadically.

XMLHttpRequest cannot load http://steamapi-a.akamaihd.net/ITowerAttackMiniGameService/GetGameData/v0001/?gameid=39650&include_stats=0&format=protobuf_raw. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://steamcommunity.com' is therefore not allowed access.

GetGameData could be GetAbilities also. Not sure if breaks anything, since it looks to be a Valve error but thought I would report it just in case.

**Comment by wchill** [comment]
This is a Valve error that occurs when the server is overloaded.
