### ISSUE TITLE
Auto-refresh Ignoring Preference?

### ISSUE THREAD

**Issue by corymcdonough** [wchill/steamSummerMinigame#110]
My game keeps refreshing despite the auto-refresh checkbox being unchecked.

I'm running https://www.reddit.com/r/SteamMonsterGame/comments/39s6z4/slave_script_increase_autoclicker_cps_and_gold/ alongside it so this might have something to do with it?

**Comment by wchill** [comment]
I am currently not sure. Can you check your browser's local storage: Look for steamdb-minigame/enableAutoRefresh.

**Comment by corymcdonough** [comment]
The slave script was refreshing. Not an issue with this script.
