### ISSUE TITLE
[Suggestion] Auto Use 'Treasure' On Bosses

### ISSUE THREAD

**Issue by Huntakillaz** [wchill/steamSummerMinigame#111]
This would make sense as is also does a free metal detector too, ideally for a Boss who has more than 60% health as per 'Raining Gold.'

**Comment by oedw** [comment]
Does metal detector affect the amount given on gold rain? I thought metal detector only increases the amount of gold dropped on the death of an enemy

**Comment by wchill** [comment]
Honestly I am thinking just use Treasure as soon as you get it. It greatly simplifies script logic and the 100k is nothing even after about 10 minutes in.

Metal detector gets spammed pretty frequently also.

**Comment by StaplerGuy** [comment]
Why not also auto-use Crit? Or is it supposed to do that and I have some other issue?

**Comment by wchill** [comment]
Crit is used ASAP to increase your critical hit chance. If it's not working for you, you may need to update.

**Comment by StaplerGuy** [comment]
Yeah, Crit's working now, but Pumped Up isn't. Is it counting it as Medics or something? Not that it matters per se.

**Comment by wchill** [comment]
Pumped Up is pretty useless, but it should basically be used just like Medics. I'll investigate whether this is actually the case.

**Comment by oedw** [comment]
Might use this thread's solution for this relevant issue: https://github.com/wchill/steamSummerMinigame/issues/42

**Comment by brendanvos** [comment]
I'm not sure if it's appropriate to continue discussion of "Pumped Up" in this thread, but here goes:

It seems like pumped up should be used under the exact same circumstances as medics, where either one is deployed, not both. Instead, health is checked twice (um what...?) and Pumped Up is used as a fail-safe in-case health drops below 50%. Honestly it doesn't really seem like we're in of such a failsafe....

```javascript
function useMedicsIfRelevant() {

    // check if Medics is purchased and cooled down
    if (hasAbility('MEDICS')) {

        // Medics is purchased, cooled down, and needed. Trigger it.
        advLog('Medics is purchased, cooled down, and needed. Trigger it.', 2);
        triggerAbility('MEDICS');
        return;
    }

    var myMaxHealth = s().m_rgPlayerTechTree.max_hp;

    // check if health is below 50%
    var hpPercent = s().m_rgPlayerData.hp / myMaxHealth;
    if (hpPercent > 0.5 || s().m_rgPlayerData.hp < 1) {
        return; // no need to heal - HP is above 50% or already dead
    }

    // check if health is below 50%
    var hpPercent = s().m_rgPlayerData.hp / myMaxHealth;
    if (hpPercent > 0.5 || s().m_rgPlayerData.hp < 1) {
        return; // no need to heal - HP is above 50% or already dead
    }

    if (hasAbility('PUMPED_UP')) {

        advLog('We have pumped up, cooled down, and needed. Trigger it.', 2);
        triggerAbility('PUMPED_UP');
    } else if (hasAbility('GOD_MODE')) {

        advLog('We have god mode, cooled down, and needed. Trigger it.', 2);
        triggerAbility('GOD_MODE');
    }
}
```

**Comment by oedw** [comment]
The double check is probably from a merge. Also only one is used, since the code returns if medic is deployed. Or are you saying to try to deploy pumped up if medic is not available disregarding whether player health is under 50%?

**Comment by csparker247** [comment]
@oedw Have you tested the solution from #42? Currently we're not using treasures at all past lvl 30 ([is this intentional?](https://github.com/wchill/steamSummerMinigame/blob/master/autoPlay.user.js#L1195)) but it seems silly to fix that one line if you're going to end up refactoring the whole function.

**Comment by wchill** [comment]
@csparker247 I'd say changing this one line
https://github.com/wchill/steamSummerMinigame/blob/master/autoPlay.user.js#L1205

should be sufficient.

**Comment by csparker247** [comment]
@wchill but doesnt the bool check on line 1195 keep treasure from being used if metal detector is on cooldown?

**Comment by wchill** [comment]
@csparker247 that's an OR. If you can use Treasure, that check passes.

Then we check if Metal Detector is active; if it is, no point in using Treasure. Return.

Then we check enemy stuff, blahblahblah

Then we try Metal Detector; if it's on cooldown or not purchased we try Treasure.

So all we need to change is the enemy health check.

**Comment by csparker247** [comment]
Yes, I know that's an OR, but we check the metal detector twice in that, not Treasure.

`if (canUseAbility(ABILITIES.METAL_DETECTOR) || canUseAbility(ABILITIES.METAL_DETECTOR))`

**Comment by wchill** [comment]
Oh, that is completely my bad. Missed that. I'll fix this.

**Comment by csparker247** [comment]
:) no worries.
