### ISSUE TITLE
[BUG] Auto Lane Not working in Firefox?

### ISSUE THREAD

**Issue by Huntakillaz** [wchill/steamSummerMinigame#114]
As Per thread: http://steamcommunity.com/groups/MSG2015/discussions/0/598198356172706881/
The lane switching has broken, iirc it was working in 3.7.x, if not then most definitely 12hrs ago from what ever the last script version was then.

It will work sometimes if you close game and resume. 

from what i can see it's not targetting the minions correctly, if i switch (manually) to a boss it targets the boss, if i switch to a non boss lane it targets lowest health but then doesn't switch to a new target after its death.

**Comment by Huntakillaz** [comment]
Console shows:

this.m_rgLaneData[this.m_rgPlayerData.current_lane] is undefined.

**Comment by wchill** [comment]
Please try updating

**Comment by Huntakillaz** [comment]
Nope still the same, though once in a lane its does switch to a new minion, only once though as far as i can tell (or possibly monsters die too fast for second switch)

**Comment by wchill** [comment]
Can you give me a full stack trace of the error? I need to know line numbers.

**Comment by Huntakillaz** [comment]
pretty much happens instantly as soon as you get ingame from console:

this.m_rgLaneData[this.m_rgPlayerData.current_lane] is undefined. running.js:1113:0
"Found existing lock on 3, locking onto it." autoplay.u...:1022:8
"Got stale data....." <-continues with this.

**Comment by alvin853** [comment]
that's still the problem with greasemonkey, it works fine if c&p the script into console

**Comment by wchill** [comment]
I'm still not sure what is causing this. Apparently some SteamDB users get the same error but it does not crash the script.

For the time being, you will have to copy paste or use Chrome + Tampermonkey, as there are no reports of this occurring on Tampermonkey.

**Comment by Techwolfy** [comment]
I have the same issue with Greasemonkey (works fine from the console), but [mouseas' script](https://github.com/mouseas/steamSummerMinigame) worked properly.

**Comment by Huntakillaz** [comment]
You seem to have fixed this.

**Comment by wchill** [comment]
Closing.
