### ISSUE TITLE
Dynamic ability/item name loading breaks with other languages

### ISSUE THREAD

**Issue by wchill** [wchill/steamSummerMinigame#115]
http://pastebin.com/pss5Ez2A

See for details.

**Comment by drantor** [comment]
Workaround browse the site on english: 
http://steamcommunity.com/minigame/towerattack/?l=english

**Comment by Harest** [comment]
Damn, now i know why abilities didn't work properly. That's strange they translate even the source code, but it's not the first time. Many issues with it in the steam profiles settings in french a while ago.
