### ISSUE TITLE
Stops working (no lane changing, clicking, etc.) after error when using nuke

### ISSUE THREAD

**Issue by Kapow751** [wchill/steamSummerMinigame#116]
This kills MainLoop:

Uncaught TypeError: Cannot read property 'position' of undefined
CSceneGame.TryAbility @ running.js?v=as8wg42t0y:1514
triggerAbility @ VM1343:972
useTacticalNukeIfRelevant @ VM1343:811
MainLoop @ VM1343:209

It seems to be caused by the game failing to load the targeted enemy:

		case 10: // Nuke
			var enemy = this.GetEnemy( this.m_rgPlayerData.current_lane, this.m_rgPlayerData.target  );
			this.SpawnEmitter( g_rgEmitterCache.nuke_black_smoke, enemy.m_Sprite.position.x, enemy.m_Sprite.position.y );

The SteamDatabase fork avoids this by having triggerAbility use the game's ability queue instead of calling TryAbility directly.

I would also wrap MainLoop in a try/catch that shows any error to the user, in case of intermittent problems like this.

**Comment by wchill** [comment]
Should be fixed for now.
