### ISSUE TITLE
Autoclicker stops working over time.

### ISSUE THREAD

**Issue by Klockwork** [wchill/steamSummerMinigame#124]
I have had this happen multiple times now. After an arbitrary amount of time the script will stop autoclicking. I just refreshed and changed it to 3.8.5 so we will see if it happens again.

**Comment by pkolodziejczyk** [comment]
It's a bug line 389 a "}" that shouldn't be there.

**Comment by wchill** [comment]
was fixed in bugfix branch, now in mainline.
