### ISSUE TITLE
Disable/Fix Health Easing

### ISSUE THREAD

**Issue by corymcdonough** [wchill/steamSummerMinigame#128]
The game has built in code to "ease" the health based on estimations. This is often inaccurate. One example is when you die prior to your health indicating you're low. 

I'm not sure how it's implemented, but I'd like to see the numbers as soon as I get them from the server instead of having the game "ease" down to them.

Alternatively, show two health bars for mobs and players - one of the actual health and one of the eased health? Or have them overlapped with different colors or something.

**Comment by wchill** [comment]
I'd have to investigate, but definitely the first one is easier to implement. It'll take some time though.
