### ISSUE TITLE
[Suggestion] Nuke some bosses down, farm on others?

### ISSUE THREAD

**Issue by StaplerGuy** [wchill/steamSummerMinigame#130]
Taking a minute and a half per boss (estimate based on today's number six game, which I'm in) seems counterproductive when the boss yield doesn't increase that much every ten levels. Would it ultimately lead to more progress to nuke down most bosses and farm on every fifth or tenth or whatever boss? Especially in the future when everyone's starting with enough Treasures and Crits that DPS starts high.

(Also, I don't know if the script has Wormhole autofire based on computer time being close to end time, but I guess I'm suggesting that too.)

**Comment by corymcdonough** [comment]
Plus the fact that we can't rejoin games means that we'll eventually run out of raining gold, which is far less valuable on the lower bosses. It might be worth it to take some more time on the low levels to gain more gold on the high ones?

**Comment by oedw** [comment]
@StaplerGuy the script uses tactical nuke on bosses whose health is between 30% and 60% and cripple monster on bosses whose health is greater than 50%. This applies on levels greater than 5,000 but not any level divisible by 250.

https://github.com/wchill/steamSummerMinigame/blob/master/autoPlay.user.js#L901-L946

**Comment by wchill** [comment]
I set it to 10000/2000 earlier today when trying to figure out what would be good numbers. Obviously those were too high.

The script has been redesigned such that changing when speedmode kicks in is now much easier, and the threshold is now lower (I estimate a 3x increase per day should work).
