### ISSUE TITLE
"Players in lane" issues

### ISSUE THREAD

**Issue by brendanvos** [wchill/steamSummerMinigame#133]
Using bf9ccf1a84 on Google Chrome 45.0.2431.0 canary (64-bit) (untested in other browsers)

When manually running the script "Players in lane" is frozen to the last count prior to launching script.
In tampermonkey this manifests as an entirely missing player count as the script begins prior to the initial display of the player count.

**Comment by wchill** [comment]
So you're saying that the display is frozen?

**Comment by brendanvos** [comment]
Yes, it happens immediately. In the last few updates  I have not seen "Players in lane" count update once the script has been run.

**Comment by Soulflare3** [comment]
I'm on Chrome Stable 43.0.2357.124 m and my "Players in Lane" count doesn't work at all, and hasn't through many versions of the script. It's not a "problem," it's just strange to see that broken.

I just updated to bf9ccf1a84cf866d4baec433982749c4e5498571 and it's still in the same state.
![screenshot](http://i.imgur.com/s7j1Zbp.png)

**Comment by xLivan** [comment]
Confirm. Google Chrome 40.0.2214.93 m x64. TamperMonkey. autoPlay.user.js 4.0.0
![wchill_steamgame_problem](https://cloud.githubusercontent.com/assets/11009293/8157728/8de3616a-135f-11e5-870a-10261acb5fee.PNG)
