### ISSUE TITLE
Valve credits blocking options firefox (v4.0.0)

### ISSUE THREAD

**Issue by DeF3ar** [wchill/steamSummerMinigame#136]
its `<div id="footer">` if you delete that its will be fixed .. 
or edit the `<div id="footer_spacer"></div>` to height: 240px; at the rules in firefox inspector .. 

[game problem](https://cloud.githubusercontent.com/assets/6254337/8153407/54cfe836-1336-11e5-91d2-8941fd4804da.png)

**Comment by oedw** [comment]
See if replacing ```<div id="footer">``` with ```<div id="footer" style="position: relative!important;">```

**Comment by DeF3ar** [comment]
Remove interface is fixing it but its remove the top interface too.
and '<div id="footer" style="position: relative!important;">' is just lowering its down more ..

**Comment by wchill** [comment]
Best option might be to make the options panel draggable.

**Comment by oedw** [comment]
@DeF3ar can you confirm this works for you? https://github.com/wchill/steamSummerMinigame/pull/155

**Comment by wchill** [comment]
Closed by #180
