### ISSUE TITLE
Crippled Monster on Boss Levels

### ISSUE THREAD

**Issue by Trouvist** [wchill/steamSummerMinigame#141]
Currently you're using Cripple Monster on boss levels %200, and not taking into account the rain level variable (which is 250).  This is HUGE.  Means you're only gonna get non-crippled bosses every 1000 levels.

**Comment by wchill** [comment]
Actually no, this looks fine to me.

````
if (level > control.speedThreshold && level % control.rainingRounds != 0 && level % 10 == 0) {
````

**Comment by Trouvist** [comment]
You are correct.  I looked again and it's correct as well.
