### ISSUE TITLE
[Suggestion] add Browser tips to game UI

### ISSUE THREAD

**Issue by RawPLowPLow** [wchill/steamSummerMinigame#147]
If this is still relevant, how about adding the "Browser tips" bit from http://steamcommunity.com/groups/MSG2015/discussions/0/598198356167623323/ on the game UI.
At least the part about minimizing or switching tabs.
The gray space next to the Easter Egg button could be a good place.

**Comment by wchill** [comment]
We're pretty limited on space unfortunately...

What I might do instead is add a link to that thread there.

**Comment by wchill** [comment]
Going to solve this at the same time as #169.
