### ISSUE TITLE
Room Joining

### ISSUE THREAD

**Issue by OverlordQ** [wchill/steamSummerMinigame#153]
Since it's already fetching commands from the steam discussion page, If the script isn't running in a room, it should fetch room IDs from a given URL and try to join them in rotation until it makes it in.

**Comment by SavageCore** [comment]
Joining should be based on https://gist.github.com/anonymous/5251d650a27aa97ecebf

Thinking out loud here but is it also possible/worthwhile to check if the current g_GameID matches after a JoinGame attempt?

Today we were getting error 400's when spamming JoinGame but sometimes after a refresh you will have in fact joined a game. 

So basically will g_GameID update correctly or require a refresh? We can then force a refresh and resume game if the JoinGame attempt was indeed successful?
