### ISSUE TITLE
[Suggestion] Limit early game Rain Gold

### ISSUE THREAD

**Issue by ZeekDaGeek** [wchill/steamSummerMinigame#157]
Right now the script auto uses rain gold, I feel like this should be an option, not something that's on by default. We are wasting 100s of Rain Gold buffs on level 10~100 bosses and getting relatively nothing out of it instead of saving them for high level bosses to get serious bank.

Maybe add the option to customize which abilities are automatically used, or just have a checkbox to disable auto using of abilities.

**Comment by Zadrox** [comment]
Could do this by dividing groups into userids, and fitting them to certain level groups, much like it's done for elemental damage. Get the last 2 digits of userid, and if it's:
odd odd, odd even, even even, even odd - do different behavior. I suppose the big problem is there's no way to know if this will follow a good distribution though.

**Comment by gapple** [comment]
mouseas/steamSummerMinigame does a random chance of using gold rain, [which increases up to level 10000](https://github.com/mouseas/steamSummerMinigame/commit/84b759a9d9d3630a016c90fd1acfe98fab57a6a8).
If bosses start taking multiple seconds there are more chances that it will get used as well.

**Comment by corymcdonough** [comment]
I agree, but it seems like we cap out at later levels anyway. The bosses + Raining Gold doesn't really generate enough to cover the hundreds-of-billion gold upgrades. We should probably find "hotspot" levels where raining gold is more or less effective.

It seems like it slows down at about level 1200. Not sure when it picks back up though.

**Comment by corymcdonough** [comment]
The game also needs to limit or hash out Nukes, Napalm, etc. Since everyone buys it around the same time, I see like 40-50 of them being used on one lane. Latency seems to sort things out eventually, but wasting an hour-long cooldown sucks.

**Comment by wchill** [comment]
See discussion in #177, there might be a good way of dealing with wasted Nukes.

**Comment by gapple** [comment]
``&&`` takes precedence, so I think it should have been 

    (level < control.speedThreshold || level % control.rainingRounds === 0) && level > control.useGoldThreshold 

instead of 

    level < control.speedThreshold || level % control.rainingRounds === 0 && level > control.useGoldThreshold
