### ISSUE TITLE
[Suggestion] Limit use of Raining Gold until later levels.

### ISSUE THREAD

**Issue by Airforcefalco** [wchill/steamSummerMinigame#158]
We had like 200 or so people use their Raining Gold ability on levels before 100. If we waited to fully commit all available Raining Gold abilities until level 500+, gold income would skyrocket.

**Comment by oedw** [comment]
Already suggested: https://github.com/wchill/steamSummerMinigame/issues/157

**Comment by Airforcefalco** [comment]
Sorry about that!

**Comment by oedw** [comment]
No problem ;)
