### ISSUE TITLE
Worm Hole + Throw Money should be spammed an hour or two before reset

### ISSUE THREAD

**Issue by Chdata** [wchill/steamSummerMinigame#162]
Throw Money At Screen:
Why don't we all spam it during the last hour or two. By then our upgrades will probably be way too high to even buy, so what other use would our gold have?

Worm holes should probably also be autospammed at that time too. Since bosses only get slower and slower over time, the longer we wait the more use we're getting out of it.

**Comment by wchill** [comment]
Closed by #161.
