### ISSUE TITLE
Some info that should probably be displayed on the minigame itself

### ISSUE THREAD

**Issue by Chdata** [wchill/steamSummerMinigame#163]
I'm sure plenty of people simple install the script and let it run...

without going to read strategy guides

or knowing how the script functions

Basically, you should probably add a line of text warning the user, "Script deactivates if you're in a different tab or if minimized! (But you can drag the window offscreen).".

and also

"Abilities such as Max Element, Monster Cripple, and Worm Hole will be used by the script when appropriate, don't worry about them!"

If you wanna get crazy, you could use the steam api to display things like how much damage the enemies were doing a level ago. (Well, maybe there's other ways to do that with just the game itself).

http://steamapi-a.akamaihd.net/ITowerAttackMiniGameService/GetGameData/v0001/?gameid=41673&include_stats=1

**Comment by Eriner** [comment]
This sounds like a lot of clutter. If this were implemented as you suggest, it would have to be in a minimizable, modular box to itself. The best idea is to just improve the script to do all of these things for you, which is mostly does (aside from auto-upgrades, which there is a PR for right now). A link to an FAQ page would be fine, and could contain all of this and more. No need to clutter the interface with useless things.

**Comment by Chdata** [comment]
At the very least I'd add the thing about having the window active next to the Room ID.

**Comment by Eriner** [comment]
That sounds like a good idea. And also a link with a page/FAQ that could include other information you mentioned. I'll whip something up here in a bit.
