### ISSUE TITLE
Base Some Abilities on Time/Level Rather than Enemy Health

### ISSUE THREAD

**Issue by corymcdonough** [wchill/steamSummerMinigame#164]
Some abilities, for example, Max Elemental Damage, should probably not be triggered unless the current level takes over 3-5 seconds. People are using it on bosses that are already dying almost instantly.

**Comment by Chdata** [comment]
In the case of Element Max, pretty much only 1 per lane should be active at any time if you wanna be optimal. In which case, as long as one is used if there isn't already one active. Considering there's a thousand players and these drop from bosses all the time, they probably won't run out.

**Comment by corymcdonough** [comment]
Yeah, I notice it stacking up as well. That should definitely be prevented.

**Comment by wchill** [comment]
Will work on adding a timer.

**Comment by wchill** [comment]
Useful variables:

g_Minigame.m_CurrentScene.m_rgGameData.timestamp_level_start

g_Minigame.m_CurrentScene.m_rgGameData.timestamp

g_Minigame.m_CurrentScene.m_nLocalTime

**Comment by corymcdonough** [comment]
Just saw 130 of these up at once. We definitely need to like ... implement both a "don't use if there's one active" and a hash to prevent usage overlap if possible. Something like:

    if( parseInt(g_steamID.slice(-2)) % 25 == level % 25 )

Just to limit the number of people trying to cast it at the same time when it's available.
