### ISSUE TITLE
[Issue] Cluster Bomb Hardly Ever Being Used

### ISSUE THREAD

**Issue by corymcdonough** [wchill/steamSummerMinigame#167]
In room 4 (41661), my Cluster Bomb has hardly (or never) been used in 7000 levels / 5 hours. Logic needs to be revisited to utilize this cooldown - it doesn't appear to be used on bosses due to there only being one target, and it's never used on creep/spawner waves because they die so quickly. Occasionally I'll see someone use theirs but I believe its a manual usage, almost never script used.

**Comment by 3xo** [comment]
Fix in  #170

**Comment by corymcdonough** [comment]
Yep, that would do it. Nice.

**Comment by campbeb** [comment]
Should be fixed by 04436e14506881b58d6016b233dbe0743c1d7417

**Comment by wchill** [comment]
Yep. Closing.
