### ISSUE TITLE
Uneven elemental distribution

### ISSUE THREAD

**Issue by DannyDaemonic** [wchill/steamSummerMinigame#168]
The best precision you can get with a Number is 53 bits [as per spec](http://ecma262-5.com/ELS5_HTML.htm#Section_8.5), but steamId is more than 53 bits, so parseInt drops bits. Even the hashing done in the script doesn't seem to entirely make up for these lost bits. I've seen some numbers that seem to back up this assertion.

What's funny is the [strategy guide](https://steamcommunity.com/groups/MSG2015/discussions/0/598198356167623323/) you (wchill) wrote seems to get this right. Since 100 is evenly divisible by 4, we can just use ```g_steamID.slice(-2)%4``` to get an element.

**Comment by Selene29** [comment]
Here is the live distribution of room 1:
http://hintswen.com/SteamGame/elemental.php?room=41671
room 2:
http://hintswen.com/SteamGame/elemental.php?room=41673

This is a nearly perfect distribution considering that there are >100 randoms

**Comment by wchill** [comment]
Yeah, I'm not going to worry about this too much. It's one more thing I have to worry about when either grabbing or submitting patches from/to SteamDB repo.

**Comment by DannyDaemonic** [comment]
People in other issues have complained about uneven distribution, but I'm not sure what percent of these people are using whose script. What actually got me started on this was the current hash code seemed rather complex for choosing what should be a single number [0-3].

In the end, I think simpler code is better. This is just one line of code:
```javascript
parseInt(g_steamID.slice(-2)) % 4
```

Even combine with room number as suggested before, it's still fairly simple:
```javascript
( parseInt(g_steamID.slice(-2)) + parseInt(g_Minigame.gameid)) % 100 ) % 4
```

The current hash method used adds 10 or more lines of code.

**Comment by corymcdonough** [comment]
@Selene29 Do we have historical data on what elements the lanes use? The even elemental distribution makes sense but only on the assumption that the lanes are evenly distributed as well.

**Comment by wchill** [comment]
Anyway, I'll patch this in for next restart. There's no point doing it today.

**Comment by wchill** [comment]
https://github.com/wchill/steamSummerMinigame/commit/f1e9971daf754014f1866bdf6396487b90f75c95

This will be pushed into the main branch one hour before reset.

**Comment by Selene29** [comment]
@corymcdonough I did not find any. The only solution would be if someone logs the enemy's elemental aptitude of all 3 lanes for every level for 1 or 2 days to see if there is a bias for a certain element.

**Comment by wchill** [comment]
Now irrelevant, closing.
