### ISSUE TITLE
[Suggestion] Have the scripts display a link on the game page to your room's IRC channel or steam group

### ISSUE THREAD

**Issue by meekmeekmeek** [wchill/steamSummerMinigame#169]
I know most of the "official" rooms have dedicated steam groups to chat in. We could also generate links (through a web-irc client website like Mibbit) and if the script added a link on the page, more people would tend to join them.

doing it for an IRC channel would be easy, since you'd just generate the URL based on the room number, even if the channel doesn't exist yet (someone familiar with IRC could go create it then): 

`http://mibbit.com/?channel=%23<channel_name (w/o "#")>&server=<server_address>`

Linking to the steam groups would be harder since I don't believe we're naming them according to game ID, so someone would need to map them, possibly in an daily update to the script, and it would end up only supporting a few official groups:
eg:

`http://steamcommunity.com/groups/MSG2015_R6`

**Comment by brendanvos** [comment]
Wow, this would be a great way to coordinate a room's efforts!

**Comment by meekmeekmeek** [comment]
To Crosspost from the ensingm2 thread where this is apparently getting some traction, the following url seems to be all that's needed to open a channel (creating it if necessary) and logging in with the specified name:

`http://chat.mibbit.com/?channel=%23SMG_41746&server=irc.mibbit.net&nick=meekmeekmeek`

for channel name "SMG_41746" and username "meekmeekmeek"

**Comment by wchill** [comment]
I'm not too concerned about URLs and such. However, I do need to figure out the CSS as it's just not coming to me.

**Comment by brendanvos** [comment]
@wchill ensingm2's implemented it looking real nice in https://github.com/ensingm2/SteamMonsterGameScript/commit/61a09298ffb0c2c7887024bc4c8d17b8999be4df
