### ISSUE TITLE
For manual "installation" instructions consider linking to raw file on GitHub?

### ISSUE THREAD

**Issue by chrisblakley** [wchill/steamSummerMinigame#17]
Just a thought to help those who aren't familiar with JavaScript or GitHub, maybe instead of having people download the repo and then open autoPlay.js in a text editor in order to select all and copy, link directly to the GitHub raw file for autoplay.js?

https://raw.githubusercontent.com/wchill/steamSummerMinigame/master/autoPlay.js

Then they can just open it in a tab, select all, copy and paste into their console.

**Comment by wchill** [comment]
I plan on minifying the script very soon, but yes that is planned.

**Comment by wchill** [comment]
Fixed.
