### ISSUE TITLE
game_frame_tv_fix.png Missing

### ISSUE THREAD

**Issue by ags131** [wchill/steamSummerMinigame#172]
This is set as background image for .tv_ui, but doesn't not exist so leaves an ugly black background.
If this is intentional, it should be optional

**Comment by wchill** [comment]
Cannot confirm. I have it hosted on imgur and it is working fine for me on 4.1.0.

**Comment by ags131** [comment]
URL resolves to https://raw.githubusercontent.com/wchill/steamSummerMinigame/master/game_frame_tv_fix.png on mine with a 404 error.

On 4.1.0

**Comment by ags131** [comment]
Well, looks like it was fixed in 1ccba9389cd47c4d972154c16b9c2b1b3909bb37 but version was never updated.

**Comment by wchill** [comment]
I will do a version bump.
