### ISSUE TITLE
[Suggestion] Restricting items/abilities to bosses at some point of the game

### ISSUE THREAD

**Issue by armetilou** [wchill/steamSummerMinigame#177]
At some point it is probably a good idea to restrict use of nuke, napalm, cluster bomb, and cripple monster, to bosses only. With the insane power of the new tiers of weapons DPS alone takes care of killing creeps, spawners, and minibosses at current levels. The DPS of the top 10 games as of this second range from 96B to 1.28T DPS, whereas in the 18000 levels creeps have HP in the tens of billions, spawners and minibosses in the hundreds of billions, and bosses in the *quintillions*.

Using anything other than DPS and cripple spawners during this stage of the game seems like a complete waste, when games regularly get stuck for long periods at bosses because everybody is waiting for a cool down.

**Comment by wchill** [comment]
I think it may be better to base it off of round times. If clients are killing regular enemies in less than X seconds per level, use abilities on bosses only. Else, enable abilities on regular enemies.

**Comment by brendanvos** [comment]
@wchill Perhaps this would benefit from a distinction between dmg per spawner level and dmg per boss level?

**Comment by armetilou** [comment]
It could possibly be based off dps info from lane data too, but I'm not sure how reliable that is. For instance, you could check g_Minigame.m_CurrentScene.m_rgLaneData[i].friendly_dps for lanes i=0,1,2 every second and average the nonzero values over, say, a minute. Then also average the max HP of the creeps over that time, and if the average dps is big enough in comparison switch over to bosses only mode.

**Comment by wchill** [comment]
Lane DPS is not reliable because abilities will affect it, which are not constant. Instead, if you wish to go that route, the best way is to calculate EDPS as shown here http://drx.pl/steamgame/ranking_41671.html

**Comment by armetilou** [comment]
Thought that might be the case. Basing it off round time seems a lot simpler to implement.
