### ISSUE TITLE
Treasure not triggering

### ISSUE THREAD

**Issue by itsdvw** [wchill/steamSummerMinigame#181]
Only just started looking at the code but it seems canUseAbility(ABILITIES.TREASURE) triggerAbility(ABILITIES.TREASURE) should be replaced with canUseItem(ABILITIES.TREASURE) and triggerItem(ABILITIES.TREASURE). Lots of extra metal detectors going unused...

**Comment by wchill** [comment]
Hmm, I thought this was already fixed. Oh well, I'll fix it.

**Comment by wchill** [comment]
Closed by https://github.com/wchill/steamSummerMinigame/commit/4995c7a137246c31319232a59b9ca147412f1c40
