### ISSUE TITLE
[Suggestion] Enforce consistent code style

### ISSUE THREAD

**Issue by welwood08** [wchill/steamSummerMinigame#184]
I'm finding myself hitting more and more merge conflicts that are difficult to deal with because the indentation of large similar-looking blocks is tabs on 1 side and spaces on the other.

Would there be much resistance to enforcing a particular style for Travis to test? I think many of the recent indentation differences were introduced when merging some of steamdb's fork, so would it be better to follow that style and enforce tab indentation or is there a preference here for spaces? Personally I'd use 4 spaces, but we're going to have constant merge conflicts with steamdb if they don't follow suit.

**Comment by wchill** [comment]
We should go with tabs.
