### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by dpressl9** [wchill/steamSummerMinigame#190]
New Meta Suggestion: Buy One Treasure (Spend this Immediately on 1 Armor Piercing Round, 10 Auto-fire Cannon, and 1 Boss Loot.) Get either 20 or 30 Crit. If you buy 20 Crit, you get 1 extra wormhole. The more who do that, the more effective that is. If you buy 30 Crit, you get 1 less wormhole. It makes a maximum of a 1500 level difference, essentially, for better or worse. Purchase exactly 10 Rain Gold, and dump the rest of your money into the following prioritization chain: Wormhole -> Rain Gold -> Treasure -> Pumped Up. Use Treasure and Pumped Up immediately. Try to get Boss Loot to 1, then get Click-Damage until ER is unlocked, so your early DPS isn't lacking since we can't rely entirely on Cripple Spawners being spammed. Work immediately to get Boss Loot to 13. This is the min-max stage. After this, continue prioritizing Click-Damage until 2-3k. In these rounds, prioritize either 14 or 15 Boss Loot. It gets expensive, but it gets the room a slight surplus on average of both Cripples needed to progress. Once Boss Loot is at 14 or 15, continue with previous meta of damage and lucky shot, however you choose to optimally build.

1 Treasure, 20/30 Crit, 10 Raining Gold, All Wormholes, Excess Rain Gold -> Excess Treasure -> 1 Pumped Up if odd Badge Points.

1 Armor-Piercing Round, 10 Auto-fire Cannon, 1 Boss Loot, Armor-Piercing Round until 10, Boss Loot until 13, Click-Damage until level 2-3k, 14 OR 15 Boss Loot, then optimal EDPS build.

**Comment by DarkLordJack** [comment]
This belongs in the steam group or subreddit not here.

**Comment by wchill** [comment]
I asked him to post it here so I could use it as reference.

**Comment by wchill** [comment]
It will be used for the autobuyer.

**Comment by StaplerGuy** [comment]
So it'll have auto-startup-buy too? Nice.
