### ISSUE TITLE
Use Wormhole on Multiples of 100

### ISSUE THREAD

**Issue by corymcdonough** [wchill/steamSummerMinigame#194]
See http://steamcommunity.com/groups/MSG2015/discussions/0/598198356180327116/

According to the new wormhole tooltip, if used on a level with a multiple of 100, it skips 10 levels instead of 1.

**Comment by wchill** [comment]
Yes, and I'm also aware that it stacks until the level is completed. Levels must be completed manually, which is when the wormholes will take effect.

I think it will be best to designate certain rounds as Wormhole rounds just like we do with RG right now.

**Comment by corymcdonough** [comment]
Perhaps on certain levels we should give a ~2 second delay for everyone to use a wormhole, then nuke as normal. Based on approximate end-time to the game people could use their wormholes so they can utilize them all by end time.

**Comment by wchill** [comment]
I feel the best approach is to estimate the number of levels being completed per second, and use that to time the spam. With a somewhat random distribution thanks to network lag, this should allow us to get a high efficiency.

**Comment by corymcdonough** [comment]
http://www.reddit.com/r/SteamMonsterGame/comments/3a220p/day_6_introduces_rollover_damage_extra_dmg/

We also have this potential problem if enemy health doesn't start increasing more significantly at higher levels. We might rollover right past one of the thresholds.

**Comment by wchill** [comment]
Yes, that's why I feel estimating the number of levels is the best approach.

**Comment by wchill** [comment]
Alternately, if we set it to every 1000 levels, we can disable the script until it's about to hit 1000.

**Comment by corymcdonough** [comment]
IMO change Raining Gold to occur every 500/1000 levels and just utilize that for wormhole skips.
We're going too fast for every 250 to still make sense, and using 500/1000 gives us plenty of time to fire wormholes.

**Comment by wchill** [comment]
Good point. I'll look into it.

**Comment by corymcdonough** [comment]
useWormholeIfRelevant() does not check if we are near endgame. Is this intentional? We'll be using wormholes a lot well before we're in the higher levels.
