### ISSUE TITLE
After a certain level Treasure! should be used on cd.

### ISSUE THREAD

**Issue by Klockwork** [wchill/steamSummerMinigame#195]
After a certain level(maybe 1k-3k?) treasure doesn't make sense to not use on cooldown or it's duration timer. The gold gain in negligible and the rooms are passing by at a rate of 1 normal every 2-3 seconds(in room 1). It also seems to be a common drop(along with throw gold, steal health, and reflect damage) that doesn't get used by the script.

**Comment by corymcdonough** [comment]
My script also isn't using Cripple Spawner enough. I've got 118 of them and counting.

Also - they changed Treasure to give you more gold at higher levels, but it does still seem to be almost negligible. I think I get around 1b for using it.

**Comment by Klockwork** [comment]
At room level 176k it's giving me 1B per click. Is there a known upper limit? It's still pretty negligible though. It looks like I am earning about 1B per refresh(with the renderer throttle on).

**Comment by aluhadora** [comment]
Submitted a pull request for this

**Comment by nbadal** [comment]
#210 was merged, this can be closed
