### ISSUE TITLE
Throw Money During Nuke Function, Not Wormhole

### ISSUE THREAD

**Issue by corymcdonough** [wchill/steamSummerMinigame#200]
Currently, the Wormhole function throws money if it can't use a wormhole.

This means we'll inadvertently burn down bosses that other people might be trying to use wormholes on.

We should be throwing money at the enemies we're intentionally DPS'ing faster, not the ones we DPS slower for gold and wormhole reasons. 

We also shouldn't be halving clicking during wormhole rounds. They're probably going faster because of Throw Money, not because of click DPS. We should be clicking for raining gold (if it exists), but the Throw Money needs to stop.

**Comment by wchill** [comment]
It does not throw money unless the game is about to end (global reset).

Halving clicking was done because early on DPS was too high and later on (after several jumps) we can stack WHs in one boss round if it lasts more than 45-60 seconds.
