### ISSUE TITLE
Past 625-650k levels you need to use boss killing abilities on bosses at 500 levels (wormhole).

### ISSUE THREAD

**Issue by Nishi77** [wchill/steamSummerMinigame#207]
They have way too much hp and the script doesn't use them. Maybe after the first gold rain ends.

**Comment by sordidfellow** [comment]
The real issue is trying to code for levels is nearly impossible.

The script should be tracking how long since a wormhole was added to the stack.  If it's been 5-10 seconds with no new wormholes, then go ahead and DPS down.  As long as wormholes are being piled on, then sit back.

**Comment by Trouvist** [comment]
Nishi, thats the opposite of what we want.  We want bosses to take ungodly amounts of time, so every WH possible gets used on them before they get nuked to zero, culminating in 1 last jump to the last boss, finishing, and then close the room out.
