### ISSUE TITLE
AutoClicker toggle is ignored on page reload

### ISSUE THREAD

**Issue by sordidfellow** [wchill/steamSummerMinigame#214]
It continues doing full speed autoclicking even if unchecked.  Adjusting log level to 4 and showing console reveals:

![image](https://cloud.githubusercontent.com/assets/730944/8200099/923abe94-1485-11e5-88dc-35aedeb5bef6.png)

Here's hoping 43983 survives by stopping upgrades!

**Comment by wchill** [comment]
Clicks are actually disabled, it just tells you how much gold you would be receiving if it was clicking.

**Comment by sordidfellow** [comment]
As best I can tell, the code calls toggleAutoClicker(event), which sets currentClickRate to either 20 or 0.

The only other relevant references to the currentClickRate is when s().m_nClicks references it, and immediately outputs it.  Additionally, the damage, crit, and gold indicator text all show that the clicks are still contributing.  If the currentClickRate was actually 0, should it be reflected in the log output and the code not creating the summarized dmg/crit/gold text?

**Comment by sordidfellow** [comment]
Ok, the issue was one of initialization, I think.

After toggling the autoclicker box back on and back off, it is properly indicating 0 cps in the console.

**Comment by sordidfellow** [comment]
Related issue: If you have auto-clicker off, and the page reloads, the box remains unchecked but it definitely is clicking.

**Comment by Trouvist** [comment]
Fixed.
