### ISSUE TITLE
[Suggestion] Script-validating Join Wrapper

### ISSUE THREAD

**Issue by meekmeekmeek** [wchill/steamSummerMinigame#217]
We keep having issues with announcing a room#, and then having people join who have the wrong script, an outdated version of the script or are just there to leech because they saw the room posted in chat.

To combat #1 and #2, I think you could write a script that:

* gives you a join button (or a console function, whatever)
* when it's clicked, checks that you have the target version of wchill's script installed (if scripts can't check for each other's presence, then maybe integrate this into the wchill's script)
* if the above check passes, retrieves the room number from a predetermined remote location (not sure how easy it is to do public-key encryption in JS, but it would probably be sufficient to reversibly hash the room id, since the main goal is to stop casual leeches joining, especially since I imagine you don't want to try distributing keys securely for this game)
* proceed to JoinGame() on the above roomId

Probably worth retrieving the target script version from a remote store too.

This doesn't help combat #3, although if it's possible to check what a steam user's highest achieved game level is, it could validate that for rooms where you want a level requirement to try WormHole spam.

Randoms could still join through Steam of course, but at least this way you could post an announcement about a new room to try a strat with, without having it flooded by people who just want any room a Mod posts.

Note that this doesn't have to be a Whills only thing. SteamDB also benefits from not having Wchills users in channels its trying a new strat in, so they could also use a system like this.

**Comment by wchill** [comment]
I can check what a user's achieved game level is, but I would rather not implement it.
