### ISSUE TITLE
Multiple suggestions

### ISSUE THREAD

**Issue by Tr3c3** [wchill/steamSummerMinigame#230]
Regarding the script:

* It might be useful to have Wormholes perma-hidden (so the script manages the casting instead of the user himself)  
* Also, having a "DON'T ATTACK/NUKE THIS BOSS, WORMHOLE JUMP IN PROGRESS" text showing up in the middle of the minigame's screen/below level number on %100 levels might help alerting some sleepyheads.

Regarding Nightbot:  

* Whenever the script is updated, it might be useful to manually update his !script string to display the current version number next to the script name.  
For example:  
wchill v4.6.1: https://github.com/wchill/steamSummerMinigame || Autobuy v0.7: https://github.com/Pawsed/SteamMonsterAutoUpgradeManager

Might add new suggestions later, thanks for reading!

**Comment by Tr3c3** [comment]
Alternative suggestion: Having the whole skill bar perma-disabled, thus letting the script manage all the skill usage.  
By perma-disabled, I mean having the skill icon and count visible, but removing the onclick="g_Minigame.CurrentScene().TryAbility(this); function from the skills being exclusively used by the script.

**Comment by phizch** [comment]
@Tr3c3 , That would prevent users from using abilities the script doesn't know about or doesn't use optimally. Throw money at the screen when money is low anyway for example.

**Comment by Tr3c3** [comment]
@phizch I agree with your point, that's why my main concern was about restricting the specific skills that are supposed to be managed by the script (like Wormhole and Like new)

**Comment by g1real** [comment]
Can't use throw money because it hurts bosses significantly apparently. The text is a useful suggestion tho.
