### ISSUE TITLE
Remove offensive upgrade buttons from UI

### ISSUE THREAD

**Issue by Snaipe** [wchill/steamSummerMinigame#234]
I feel that a lot of people will still upgrade offensive abilities, maybe the upgrade buttons should be disabled at first while leaving the health upgrades.
Same thing for abilities to prevent people from buying nukes/napalm/cluster bombs for the first massive jumps.

**Comment by Klockwork** [comment]
What happens with the WH strat once the player runs out of WH?

**Comment by 5boro** [comment]
We choose new room numbers, join and buy more wormholes

**Comment by Snaipe** [comment]
Not relevant anymore
