### ISSUE TITLE
Disable napalm before other abilities when approaching WH rounds

### ISSUE THREAD

**Issue by Detest** [wchill/steamSummerMinigame#241]
Because naplam lasts for 10 seconds, they later ticks of the ability are killing bosses on WH rounds. So Napalm needs to be disabled for atleast 10 seconds before a WH round comes up.

**Comment by veniversum** [comment]
control.rainingSafeRounds just needs to be set at a higher value.

**Comment by Zazcallabah** [comment]
we speed through levels at a very high pace. The main game loop is set at 1 second @ https://github.com/wchill/steamSummerMinigame/blob/master/autoPlay.user.js#L1444
Combine this with network lag around one quarter of a second and you will get clients thinking we are on levels 95-99 modulo 100, when we actually are on a boss level.

Thus many nukes and other offensive abilities trigger when they shouldnt. I propose that the rainingSafeRounds from https://github.com/wchill/steamSummerMinigame/blob/master/autoPlay.user.js#L1035 should be applied also in the useTacticalNukeIfRelevant- and useClusterBombIfRelevant-methods.
