### ISSUE TITLE
Auto Room Joining for loyal (strategy) players

### ISSUE THREAD

**Issue by Dreamcooled** [wchill/steamSummerMinigame#249]
As various people pointed out at http://www.twitch.tv/ulletical/, we're still slowed down by people using nukes on the n*100 lvl bosses, causing big WH Jumps to be wasted.
You could modify the script as follows:
* Introduce a new "strategy mode", which when active will disable all abilities and features which go against the current strategy.
* Make a jsonp request to a c&c server and send the steamid of the player and whether or not he's currently in "strategy mode". Keep the connections open (=long-polling-requests).
* Collect stat's on server side.
* if you want to start a new room with loyal strategy players return the game-id of the new room to those jsonp requests, before anouncing it on twich.tv
* Show a dialog to the "strategy users" and ask them to join the new room.

Tell me what you think and feel free to ask if you have any questions regarding implementation :)

**Comment by wchill** [comment]
same origin domain policy is in effect (which is what led to the shitstorm yesterday). That makes this impossible

**Comment by Dreamcooled** [comment]
You could elaborate a bit more? I probably missed that.

**Comment by Dreamcooled** [comment]
I see, the Content Security Policy stuff blocks JSONP as well.
What about using a simple covert channel?
e.g. insert an image in the DOM:

    jQuery("body").append("<img src='http://example.com/da_image.png?steamid=12323232' id='bla'>");

and later query it's width and height to get the room info out of it :) ?

      var roomid = jQuery("#bla").height() * jQuery("#bla").width()

And for users which should not receive the roomnumber, you simply don't response or send a 1x1 image back.

**Comment by Dreamcooled** [comment]
@wchill @Trouvist
Any updates here? Do you plan on implementing a autojoin-script (e.g. for elite players)?
Do you need/want any help on this?
See also [my reddit post](http://www.reddit.com/r/SteamMonsterGame/comments/3a8aur/do_we_need_private_lobbies_and_a_autojoin_script/) where I elaborate a bit more on how such a autojoin system could work (and how to rule out random players and griefers)

**Comment by g1real** [comment]
Autojoin is somewhat out of the bounds of what this script wants to do, and I think that was the main reason it hasn't be done yet.

That and it's just a lot of work for a small payoff and it's 2 (1?) days left now.

**Comment by Dreamcooled** [comment]
And it has been done by now anyway.
See http://www.reddit.com/r/SteamMonsterGame/comments/3aagtj/lobby_system/
Closing this.
