### ISSUE TITLE
Possible solution to maximize time on 100 bosses. (Also prevent some of the nukes).

### ISSUE THREAD

**Issue by TUTAMKHAMON** [wchill/steamSummerMinigame#257]
So my idea is to lock the player to a lane that is not the one where the boss is, reducing the DPS on the boss. This way, even if the player were to use nukes, they would not harm the boss.

A problem with this would be that the players would be split between two layers reducing the efficiency of the "Like New"s. So to solve this we would just have to make a consistent system like for example always move the player to the right of the boss wrapping around at the end:
    >  lane = (boss+1)%3

When I say lock the player I mean change him to the intended lane and removing the other lane buttons, which could simply be done by doing something like:

   >  movePlayerToLane(boss+1%3);
   >
   >  switch (boss){
   >      case 0: // player should be at lane 1
   >          document.getElementById("lane0").style.visibility = "hidden";
   >          document.getElementById("lane2").style.visibility = "hidden";
   >          break;
   >      case 1: // player should be at lane 2
   >          document.getElementById("lane1").style.visibility = "hidden";
   >          document.getElementById("lane0").style.visibility = "hidden";
   >          break;
   >      case 2: // player should be at lane 0
   >          document.getElementById("lane2").style.visibility = "hidden";
   >          document.getElementById("lane1").style.visibility = "hidden";
   >          break;
   >      default: // default could be used as reset when not on a 100 boss level
   >                   // by using boss as -1 or something like that
   >          document.getElementById("lane0").style.visibility = "visible";
   >          document.getElementById("lane1").style.visibility = "visible";
   >          document.getElementById("lane2").style.visibility = "visible";
   >  }

I haven't analysed your script, so I couldn't provide a more specific approach on this (this is just a mockup), but I trust it shouldn't be too hard.

For any questions just add me on steam (TUTAMKHAMON) as I'm not too active on git.

**Comment by wchill** [comment]
Nukes are not being used by the script. When it happens due to lag, it is already too late to lock the lanes.

Any trolls can simply just refresh and unload the script to manually use abilities.

**Comment by ryantheleach** [comment]
This strategy also helps, as people using like news in other lanes won't be feeding the "trolls" the like new effects, only those who are swapped to the sneakylane can get the effects of the like new to continue wormholing, anyone fighting spends their abilities and thats it.
