### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by goldjee** [wchill/steamSummerMinigame#26]
Installed script using Tampermonkey on latest Chrome. Seems the script isn't working at all. Getting an error in console:
ERROR: Execution of script 'Monster Minigame AutoScript' failed! Cannot read property 'CurrentScene' of undefined
![image](https://cloud.githubusercontent.com/assets/7242338/8144315/fe15413c-11df-11e5-9168-62787c52975a.png)

**Comment by wchill** [comment]
Tampermonkey tries to run the script before the game has even loaded. I can probably fix this but it's not a huge priority right now

**Comment by kiradotee** [comment]
Just to add to that, I "fixed" it by manually putting the script into the "console". So if I see TamperMonkey not working I just manually run the script.

**Comment by wchill** [comment]
Yeah, someone submitted a pull request to check if the game has loaded based on a timer which might work to solve this. Don't want to merge it in yet though.

**Comment by matirion** [comment]
It checks if the upgrades are loaded in by checking if getElementById("upgr_0") isn't null, as thats the last thing the game loads before it's done. If it isn't loaded, it waits 3 seconds before trying again. But yes, it was because of this issue, although in my case it was with greasemonkey.

**Comment by wchill** [comment]
See if script is working now, someone submitted a cleaner Greasemonkey patch.

**Comment by matirion** [comment]
I can confirm the new patch works for GM, can't test it on tampermonkey though.

**Comment by costia** [comment]
Didn't work in tamper monkey for me
had to change 
	trt_oldCrit = window.g_Minigame.CurrentScene().DoCritEffect;
	trt_oldPush = window.g_Minigame.m_CurrentScene.m_rgClickNumbers.push
to:
	trt_oldCrit = g_Minigame.CurrentScene().DoCritEffect;
	trt_oldPush = g_Minigame.m_CurrentScene.m_rgClickNumbers.push

(remove "window.")

**Comment by goldjee** [comment]
Latest version in tampermonkey. Not working, as costia said in the above comment.
![image](https://cloud.githubusercontent.com/assets/7242338/8144702/54deab94-11f3-11e5-9d6e-21513eddf966.png)

**Comment by costia** [comment]
I had to remove all "window." preceding game variables. Otherwise removing text and particle effects doesn't work

**Comment by goldjee** [comment]
confirmed: removing "window" in

**Comment by goldjee** [comment]
*closed accidently*
