### ISSUE TITLE
Regarding Reports.

### ISSUE THREAD

**Issue by mrdigan** [wchill/steamSummerMinigame#260]
In the current issue of the script 4.7.1 any character names that show up in the ability menu aren't able to be copied. So if a person is griefing and they have special characters in their name we are unable to report it. Such as a name like this.
http://puu.sh/isXNP/a49a02e016.png
If you could input a table onto the page with the information it would help tremendously.

**Comment by GoldenJz** [comment]
They should be posted to the client If I'm not mistaken. What Room was this in?

**Comment by mrdigan** [comment]
This is in room 45200
I'm getting all the reports in the box. But if anyone has a weird name. I can't copy it.
http://puu.sh/isYHZ/a628fb3443.png

**Comment by GoldenJz** [comment]
"accountid": 29845544,
"name": "|ACG| MönkëyRÃpëř™"

"accountid": 175985327,
"name": "Lestnes"

Use http://steamapi-a.akamaihd.net/ITowerAttackMiniGameService/GetPlayerNames/v0001/?input_json={%22gameid%22:%2245200%22} to get their names

**Comment by mrdigan** [comment]
Awesome, thank you.
