### ISSUE TITLE
Script still using offensive abilities

### ISSUE THREAD

**Issue by samwisethetired** [wchill/steamSummerMinigame#262]
It strikes me that one way to reduce DPS on boss levels would be to prevent /ANYTHING/ that increased damage being used, including Steal Health, Pump Up and Reflect Damage. Since the script auto-uses these abilities at the current time, if someone were to use a Get Lucky during a boss round there could easily be a hundred of each on the board, which can't be helping to keep damage low. I suggest using these abilities is turned off entirely, since they have no particular use in the new low damage strategy.

**Comment by g1real** [comment]
DPS on boss levels isn't relevant. The percentage based nukes are.

**Comment by samwisethetired** [comment]
Fair enough. I presume in this case that the Team DPS counter includes the damage from Nukes and the like?

**Comment by g1real** [comment]
It does.
