### ISSUE TITLE
[Minor] Log of abilities used doesn't list the nukers

### ISSUE THREAD

**Issue by Harest** [wchill/steamSummerMinigame#263]
Hi,

I'm using the script v4.7.1 in Firefox (room 45195) and except the yellow alerts of players using single wormholes, i've never seen the red ones about nukers. One red for a "throw money at screen" on a lvl x00 and that's all, despite i saw the nuke icon in the icon lists above the ability log.  
Here for instance : ![img_nolognuke](https://i.imgur.com/2dNPO94.png).  
It was on 2 727 000 i believe.

**Comment by wchill** [comment]
The log does not catch everyone. Imagine what happens when you don't have the script and the room uses 3000 WH in one second. Your browser would be completely fucked.
