### ISSUE TITLE
[Suggestion] Don't switch lanes

### ISSUE THREAD

**Issue by phizch** [wchill/steamSummerMinigame#286]
Switching lanes takes one second that could be better used.
How about we instead place players in a set lane based on SteamID like with the locked abilities.
The mobs in a lane gets destroyed in less than a second anyway, and wormholes are global.
There will be less raining gold, but we could go to the boss lane on gold rain levels.. Of course, since autoclick is disabled on those it might not be that useful :-)

**Comment by MayeulC** [comment]
LN are per lane on x00 levels anyway, so we need to get into the same. see https://github.com/wchill/steamSummerMinigame/issues/265
With that said, I think you are right. steamID%3 might do the trick, or we could choose a random room at the start of the level.
Well, thinking about it... don't valve's servers already do this to some extent ?

**Comment by phizch** [comment]
True enough, but if the theory that LN disables cooldown on WHs used during the duration of the LN, then it shouldn't matter that the players are split 3-ways.
Still, moving them to the boss lane is the safest bet.

Not sure what you meant by the last sentence - what does valve's servers do?

**Comment by g1real** [comment]
>but if the theory that LN disables cooldown on WHs used during the duration of the LN

It doesn't.

What he meant was that valve's servers drop you in a random room, I'm not sure about that, could be left lane or middle lane.
