### ISSUE TITLE
[Suggestion] Increase gold rain level % near endgame

### ISSUE THREAD

**Issue by phizch** [wchill/steamSummerMinigame#287]
I noticed that the last hour was a complete mess. Nuking and otherwise blasting gold rain bosses. I get the rationale, but if we instead of having a free for all, we increase the modulus to 500 or 1000 or something, those with wormholes can still get more effect out of them.

Perhaps a time limit can be put in place, so if no wormhole is used in 5-20 seconds it's back to free for all.

**Comment by g1real** [comment]
The nuking was because of https://github.com/wchill/steamSummerMinigame/issues/284
