### ISSUE TITLE
Not allowing any Element Upgrade selection

### ISSUE THREAD

**Issue by daisukepr** [wchill/steamSummerMinigame#288]
Not allowing any Element Upgrade selection with latest version

**Comment by veniversum** [comment]
Intended. https://github.com/wchill/steamSummerMinigame/commit/c7264e5a2ec3ca8dbb56f17538d71df86afb9b09

**Comment by daisukepr** [comment]
I see.  What's the intention for not allowing any?

**Comment by wchill** [comment]
Not needed anymore.
