### ISSUE TITLE
[Suggestion] x1000 & x10000 buying for wormholes

### ISSUE THREAD

**Issue by Huntakillaz** [wchill/steamSummerMinigame#290]
With such high levels of badges points, we need this multiplier for buying in order to buy faster and less clicking/tapping.

**Comment by g1real** [comment]
You can click the normal buy button and enter an amount.

**Comment by Huntakillaz** [comment]
true but clicking is faster than typing the amount :)

**Comment by g1real** [comment]
You wish ;)
