### ISSUE TITLE
Potential anti-troll help mechanic:

### ISSUE THREAD

**Issue by smartalco** [wchill/steamSummerMinigame#291]
So the primary way trolls are trolling right now isn't via nuking the x00 levels, it's wormholing the x98/x99 levels so we never hit a x00 level.

Solution? Nuke the shit out of the x98/x99 levels so that they go by as fast as possible.  If every script running saved their tactical nuke for the 2-4 levels before the x00 boss, I think we could reduce the amount of wormholes that are screwing us over.  And every x00 level has LNs used, so the nuke is going to be immediately reset then anyway.

Thoughts?

**Comment by veniversum** [comment]
If i'm not wrong, overkill damage is recorded and applied to following levels. If everyone nukes the 98-99 wave it can very well skip the 100th level every time.

**Comment by smartalco** [comment]
I thought that was just for click damage.  The tactical nuke at least says 'damage to current target'.  Could also use a shitton of cripple monsters on x98-99, since those just reduce a monster to 1hp, so there is no carry-over.  Obviously can't use Napalm.  Not sure about cluster bombs, since it's not single target.

**Comment by teslaTrooper0** [comment]
even then lag would have nukes going off on the x00 level

**Comment by lantaarnappel** [comment]
Or disable the nukes (and other spells a few levels before x00. I'm not sure, but i think almost everybody has a script, so maybe the trolls have them too.
