### ISSUE TITLE
List of Nukers

### ISSUE THREAD

**Issue by Dreamcooled** [wchill/steamSummerMinigame#293]
You could display a list of the current nukers underneath the monitor, together with the number of times they did it.
Something like a "wall of shame"

**Comment by brendanvos** [comment]
Harassment is not something we as a community should be encouraging

**Comment by koolkdev** [comment]
It isn't harassment. It helps to find players who thinks that they are helping by nuking bosses and explain to them our strategy. It worked good so far.

**Comment by veniversum** [comment]
I have created a separate tool for that purpose if you are interested: https://github.com/veniversum/steam-monster-game-offending-players-finder

Displaying the list to everyone seems unnecessary.

**Comment by Dreamcooled** [comment]
@veniversum nice script. 
and as I see, you are in the right room 46100 :)
