### ISSUE TITLE
[5.1.0] WH are only used on x00 levels

### ISSUE THREAD

**Issue by Harest** [wchill/steamSummerMinigame#310]
Hi,

I'm in the room 46569 with the 5.1.0 script. I've obviously refreshed the page, i'm using GreaseMonkey. I just tried disabling it to do a manual copy/paste. Same problem.  

I tried to up the log level but it seems there's no logging for it. Dunno what can i do to help you find the issue.

Edit : Temp fix : i just turned WormHoleConstantUse to true.

**Comment by g1real** [comment]
Realise I'm late, but don't set it to true anymore.
