### ISSUE TITLE
[Suggestion] Use wormholes and like news in non-boss lanes on x00 levels

### ISSUE THREAD

**Issue by mmnumbp** [wchill/steamSummerMinigame#313]
This isn't my original idea, but someone suggested using like news and wormholes in a lane other than the boss lane. Like news only refresh the current lane; if you're not in the boss lane, nukes won't get refreshed. Of course, people could just switch to the like new lane, but that requires more work for the troll.

**Comment by g1real** [comment]
pls read previous issues
