### ISSUE TITLE
[Fatal bug] Wormholes will be spammed all day tomorrow on non-%100 levels

### ISSUE THREAD

**Issue by Zantier** [wchill/steamSummerMinigame#315]
Please see the comments on 2f48ebae4f9ff01ea7f4e1e1ee128d4f6471e82c

Although it will still be a problem today, as people will have so many wormholes tomorrow, the problem will be exacerbated greatly. People will have enough wormholes that they will be spammed right from the start.

Particularly with a recent commit 66edde32f77821c1b1f9b8fe745f084e721ddec7!! Changes should be tested or at least proof-read before committing to master. Correct me if I'm wrong, but `remaining_time` counts down from 24 to 0, so `wormHoleShouldSkip = (remaining_time < remaining_wormholes * 1000);` will always be true if you have any wormholes.

**Comment by g1real** [comment]
You're right. Reverted the change.
