### ISSUE TITLE
[Suggestion] Hybrid wormhole / sequential on non %100 levels

### ISSUE THREAD

**Issue by skramblers** [wchill/steamSummerMinigame#316]
Rather than just jumping all the time and hoping to land on Gold Helm, maybe we could also stop jumping if we land in a level range before him, like x90-x99 and run sequential to x00? This would cut down on the damage carryover onto the boss. The only thing we would lose is a couple seconds grinding through a few levels to a guaranteed Gold Helm. Landing just short and knowing that you can't hit the target right in front of you also hurts chat/group morale.

**Comment by g1real** [comment]
Already thought of it, lag makes this an issue still.
