### ISSUE TITLE
[Suggestion] Switch to offlane on non-wormhole rounds, so our 'Like New' wont refresh troll Nukes/Napalms/etc.

### ISSUE THREAD

**Issue by NormenKD** [wchill/steamSummerMinigame#319]
Inspired by YeOldeWH.

This should limit available DMG on Boss

**Comment by SM411** [comment]
It will not work if trolls uses modified version of wchill.

**Comment by NormenKD** [comment]
If they run modified scripts it won't work, thats right.
It just makes sure that Bossnukers and Random People don't get refreshed by our 'Like New', which might help at least a little bit.

**Comment by wchill** [comment]
Closed by #320
