### ISSUE TITLE
Custom MSG 2015 UI for the last day?

### ISSUE THREAD

**Issue by SteamMSG2015** [wchill/steamSummerMinigame#324]
New UI made custom for the MSG2015 group maybe to be used for the last day of the game?

http://i.imgur.com/zHI6C6X.png

Super easy to implement, and it just looks clean. Steam badge replaced with MSG 2015 and GabeN moved so he's no longer in the way of any of the UI elements.

Just replace line 54,
		"Wormhole Gaben": "http://i.imgur.com/6BuBgxY.png"
with this as lines 54 and 55
		"Wormhole Gaben": "http://i.imgur.com/6BuBgxY.png",
		"MSG2015": "http://i.imgur.com/zHI6C6X.png"
to add it to the dropdown so it can be selected.

Hope you like it.

**Comment by wchill** [comment]
Implemented it
