### ISSUE TITLE
Getting Uncaught TypeError un script being ran, with latest version.

### ISSUE THREAD

**Issue by YannickMG** [wchill/steamSummerMinigame#336]
Uncaught TypeError: Cannot read property 'toString' of undefined
    at getPreferenceBoolean (<anonymous>:942:42)
    at <anonymous>:32:26
    at <anonymous>:1827:2
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)

This is when used in the console of Chrome.

This kills the script.

**Comment by eminarslan** [comment]
+1

**Comment by HobbitCraft** [comment]
Yep, same thing here

**Comment by eminarslan** [comment]
@wchill @Trouvist

**Comment by wchill** [comment]
Hmm, not sure. We haven't made any changes to that part of the code for days.

**Comment by eminarslan** [comment]
functioning properly with chrome extension, for now.

https://github.com/wchill/steamSummerMinigame/raw/master/chrome_extension.zip
