### ISSUE TITLE
The script won't start, here's the error message.

### ISSUE THREAD

**Issue by FlexMan39** [wchill/steamSummerMinigame#339]
http://i.imgur.com/3yx2OFB.png

**Comment by tleunen** [comment]
This is the problem: https://github.com/wchill/steamSummerMinigame/commit/21acefdf980d071baf6702bada850e56e155620a

@wchill

**Comment by wchill** [comment]
Fixed.

**Comment by tleunen** [comment]
Use the double negation would have fixed it since it force to cast the value in boolean ;)

**Comment by wchill** [comment]
Yeah, but checking for undefined works as well. Figured I might as well stay consistent
