### ISSUE TITLE
Error when using extension

### ISSUE THREAD

**Issue by camalot** [wchill/steamSummerMinigame#345]
I get the following error when i load the game with the extension, when i run the scripts in tampermonkey it works fine. I have tried disabling my adblock but that had no affect.

Refused to frame 'http://www.yimgr.com/support/www/delivery/afr.php?zoneid=5&refresh=110&cb=1434844312819&beacon=a9bccca9&n=a96a5169' because it violates the following Content Security Policy directive: "frame-src 'self' http://store.steampowered.com/ https://store.steampowered.com/ http://www.youtube.com https://www.youtube.com https://www.google.com".
init @ support.js:82(anonymous function) @ support.js:100

**Comment by wchill** [comment]
This is a Valve issue. Don't worry about it.

**Comment by camalot** [comment]
The thing is, the extension doesn't work when I get this error and I only get this error when I use the extension.
