### ISSUE TITLE
Errors in Trouvist's code.

### ISSUE THREAD

**Issue by hptwo** [wchill/steamSummerMinigame#349]
In the expression
if (medicChance < Math.Random())

'medicChance' does not resolve since he does not prepend it with 'control.' nor does the call to Math.random() since he capitalizes 'random'.

The expression should be
if (control.medicChance < Math.random())

Same mistake in the expression
if (goodLuckChance < Math.Random())

The expression should be
if (control.goodLuckChance < Math.random())

**Comment by ReklatsMasters** [comment]
i fix in #348
