### ISSUE TITLE
Game jamming

### ISSUE THREAD

**Issue by di57inct** [wchill/steamSummerMinigame#351]
I'm getting an error from version 7.4.0 and the game is freezing.

VM194:1243 Uncaught TypeError: Math.Random is not a function

Running the scripts via Chrome with Tampermonkey.

http://s8.postimg.org/fq3yyggg5/Untitled.png

**Comment by Tom910** [comment]
Fix the error - https://github.com/Tom910/steamSummerMinigame/blob/master/autoPlay.user.js

**Comment by Tom910** [comment]
Fix the error - https://github.com/Tom910/steamSummerMinigame/blob/master/autoPlay.user.js

**Comment by wchill** [comment]
Fixed in https://github.com/wchill/steamSummerMinigame/commit/1e903c017fca3d164398c515b2f4ab2d05e3fdfd
