### ISSUE TITLE
[Extension][Monster Lobby] Connection violates document's Content Security Policy

### ISSUE THREAD

**Issue by brendanvos** [wchill/steamSummerMinigame#352]
Don't know why this is occurring, but it's happening constantly. This leaves the lobby UI saying "SYSTEM Initiating connection."

Refused to connect to 'http://188.166.36.23:3900/pollen/76561197996863758' because it violates the following Content Security Policy directive: "connect-src 'self' https://steamcommunity.com http://steamcommunity.com https://api.steampowered.com/ http://steamapi-a.akamaihd.net/ https://steamapi-a.akamaihd.net/ http://cdn.akamai.steamstatic.com/ https://cdn.akamai.steamstatic.com/ https://steamcdn-a.akamaihd.net".
XMLHttpRequester.request @ MonsterLobby.user.js:131
codetorex.github.io/SteamMonsterLobby/MonsterLobby.user.js:131 Uncaught SecurityError: Failed to execute 'open' on 'XMLHttpRequest': Refused to connect to 'http://188.166.36.23:3900/pollen/76561197996863758' because it violates the document's Content Security Policy.

**Comment by almidar** [comment]
The issue is still there.
OPTIONS http://188.166.36.23:3900/pollen/76561197974829130 net::ERR_CONNECTION_REFUSEDXMLHttpRequester.request 
@ MonsterLobby.user.js:133PollenClient.request 
@ MonsterLobby.user.js:201(anonymous function) 
@ MonsterLobby.user.js:214
XMLHttpRequester.request.xmlhttp.onerror 
@ MonsterLobby.user.js:128

**Comment by kz-lt** [comment]
Try click the refresh button on the extension page (for the extension)

**Comment by almidar** [comment]
this comment isn't helpfull and its even not related to the issue.

**Comment by kz-lt** [comment]
your comment itself is not related to the original. the original is due to content security policy, yours is due to the server just being down. please think again! :)

**Comment by kz-lt** [comment]
also, my comment is related to the issue as that was what i had done to fix it on my end (if you had recently updated the extension, it needed to be reloaded.)

**Comment by camalot** [comment]
I also have this issue. I am running chrome Version 44.0.2403.52 beta-m (64-bit)

**Comment by brendanvos** [comment]
With the newest version of the script (1.5.1) I am no longer having this issue. Be sure to update your extensions!

**Comment by LeonardKoenig** [comment]
still getting this.

**Comment by LeonardKoenig** [comment]
It should be declared here:
https://github.com/wchill/steamSummerMinigame/blob/master/chrome_extension/manifest.json#L34
but I don't get it.

**Comment by camalot** [comment]
@LeonardKoenig delete the extension completely and then install 1.5.1. Delete the extension from chrome and delete the folder that contains the file. That is how I fixed it.

**Comment by LeonardKoenig** [comment]
This is a weird solution, didn't work for me anyway.

**Comment by LeonardKoenig** [comment]
I know why it won't work with with declaring it in the manifest.js now, I guess. The script tha tries to connect to
http://188.166.36.23:3900/pollen/*
is not part of the extension as it is loaded from a website itself, too.

**Comment by LeonardKoenig** [comment]
chrome_extension/js/background.js#20 seems to not work

**Comment by wchill** [comment]
We are unable to reproduce.

**Comment by LeonardKoenig** [comment]
I have made another issue (referenced) as this one is closed. I will post updates there (eg. my specs).
