### ISSUE TITLE
rainingGold

### ISSUE THREAD

**Issue by costia** [wchill/steamSummerMinigame#36]
Looks like it is being set unconditionally to true in line 259 and disables abilities:
rainingGold = true; 
assuming intended behaviour was :
 rainingGold = (stacks>0);

**Comment by BuddhaBuddy1** [comment]
This is probably why you can never use any abilities besides Medics.

**Comment by BuddhaBuddy1** [comment]
Ahh, the real issue is missing curly braces around the indented block.

**Comment by BuddhaBuddy1** [comment]
Verified. I added curly braces at the end of the "if" line and after the commented log line, and my abilities now work outside of big boss battles. but they are completely unavailable until he is dead. Also, I checked to see if I could switch lanes, and one of the OTHER lanes had raining gold, but it didn't switch over, even though the boss was at nearly full health. That seems like a big waste of a gold opportunity.

**Comment by wchill** [comment]
Fixed thanks to codebase switch
