### ISSUE TITLE
Use the pointer to show which enemy is being attacked with auto clicker

### ISSUE THREAD

**Issue by ZucchiniZe** [wchill/steamSummerMinigame#37]
this script uses the new player pointer to show you what enemy is being attacked https://github.com/ensingm2/SteamMonsterGameScript/blob/master/automator.js#L793-L798

I would implement it but I am about to go to bed right after I join the new game

**Comment by oedw** [comment]
@wchill Can be closed: https://github.com/wchill/steamSummerMinigame/commit/b3ce3ef47acd55a09fa05ec0e6491974e7cc4ef6#diff-2400c5b9c09e41abca684af32c0de223
