### ISSUE TITLE
Lane switching not working

### ISSUE THREAD

**Issue by demonhotrod** [wchill/steamSummerMinigame#38]
Was using the latest version of the script (version 2.00) and the lane switching wasn't working

**Comment by NickSC** [comment]
Same issue has started for me. It was working fine, then I reloaded the page and it refuses to work in Chrome and Firefox.

Steam changed some JS?

**Comment by tleunen** [comment]
Same for me.
This message appears in the console `Switching to a lane with best raining gold benefit` but it never switches

**Comment by wchill** [comment]
It is very likely due to lag.

**Comment by NickSC** [comment]
It's definitely not lag. It works fine if I manually switch lanes, plus it was the same amount of lag before reloading the page when it suddenly stopped working.

**Comment by Nevcairiel** [comment]
Make sure to buy at least one auto-fire cannon.

**Comment by AltairDusk** [comment]
Something is going wrong when determining which target/lane to choose.  I added a log output of targetFound after the loop and it is always false.

**Comment by demonhotrod** [comment]
Buying the auto-cannon as Nevcairiel suggested, seems to of fixed it

**Comment by AltairDusk** [comment]
Confirmed, just bought 1 auto-cannon and it is now working properly.  The bug appears to be isolated to having no points in auto-cannon.

**Comment by tleunen** [comment]
The auto-canon resolved it. Good to know. But why is it needed?

**Comment by ethan240** [comment]
Buying 1x Autocannon fixed it for me too.

**Comment by kratsg** [comment]
Buying 1x Autocannon also fixed it on my end.

**Comment by kz-lt** [comment]
:+1: 1x Autocannon :shipit:

**Comment by wchill** [comment]
Here's my theory on why Auto cannon is needed: 

After an enemy dies, the target does not normally switch. However, if you have Auto Cannon, then because it's designed to do damage while you're AFK, it'll switch the target for you. (This includes onto another lane.)

Just a theory. Easy to fix by buying autocannon.
