### ISSUE TITLE
Elemental upgrade buttons missing

### ISSUE THREAD

**Issue by Bootleader** [wchill/steamSummerMinigame#41]
Elemental upgrade button icons are missing after you upgrade one element only that element will appear as an available upgrade. Some ability icons are also missing. Happens in Firefox and Chrome.

**Comment by veniversum** [comment]
This is a feature. Edit the following line to unlock elements after upgrade.
`var lockElements = false; `

Nuke/damaging abilities are disabled during boss fights and gold rain to maximize gold gain for everyone

**Comment by kratsg** [comment]
This seems like a terrible feature. Why are elemental upgrades locked?

**Comment by wchill** [comment]
This is to coordinate elemental upgrades for the Steam group. If you don't want to follow along, just disable it.

**Comment by kiradotee** [comment]
> This seems like a terrible feature. Why are elemental upgrades locked?

As someone mentioned in some chat: "Because we are not allowed to think now".
But really, this is super useful. People otherwise will be upping more than one element (I did so before), plus nuking the boss at the same time ...

**Comment by kiradotee** [comment]
Btw wchill, do you know how it coordinates us and if it looks at specific room number and do so based on that as well?

**Comment by wchill** [comment]
It does not use room number at all to coordinate. Instead it takes your SteamID64, runs it through a hash function and then takes that mod 4 to determine which element you should spec.

**Comment by kratsg** [comment]
@wchill Oh, I was wondering why it disabled all but one for me. I have 20 on fire, and it disabled all but air. I mean, I totally get the specialization. It would be nice to have a warning about it :P

**Comment by wchill** [comment]
Yeah, I'm gonna fix that. SteamDB guys modified my element lock to be much better, so I'm going to pull that change.

**Comment by kiradotee** [comment]
Ah, I thought we had a server or whatever to which we would send the room number and it could make balanced decisions. :) Hope the SteamID64 method is balanced enough.
