### ISSUE TITLE
Will this use treasure as well as raining gold?

### ISSUE THREAD

**Issue by ryantheleach** [wchill/steamSummerMinigame#42]

**Comment by oedw** [comment]
Nope :(

Someone is working on it on a different fork and will probably add it: https://github.com/SteamDatabase/steamSummerMinigame/pull/54

**Comment by oedw** [comment]
https://github.com/RockyTV/steamSummerMinigame/commit/c10eebe6f01e4453ff676a1c03f13872d3de8320

Will test and submit a pull request

**Comment by wchill** [comment]
Finally, closed by https://github.com/wchill/steamSummerMinigame/commit/f30fbc99e847a31583326cbfd8d965a2f4c8ce45
