### ISSUE TITLE
Stuck in one lane with no enemies.

### ISSUE THREAD

**Issue by kiradotee** [wchill/steamSummerMinigame#43]
I've just noticed I was in lane 2 with 0 enemies when there were enemies in lane 1 and lane 3.

**Comment by kiradotee** [comment]
I guess it decides that because of some cool abilities being used on the lane, not sure if this needs to be fixed at all.

**Comment by kiradotee** [comment]
But it might prevent some lanes to be cleared fast if others will be stuck in some empty lane. :p

**Comment by kratsg** [comment]
See #38

**Comment by kiradotee** [comment]
I have Autocannon, they are probably saying that their script isn't switching lanes at all, mine switches them perfectly (because of Autocannon I guess), it's just it's possible to get stuck on a lane with 0 enemies, when I choose other lanes with enemies I get thrown back to the empty lane.

**Comment by kiradotee** [comment]
This doesn't happen 100% of the time, I spotted this just once. I assume it is either because of some sweet abilities that the script likes in that specific lane or some voodoo magic.

**Comment by ProfessorKaos64** [comment]
I've had this happen, for me, I just needed to add autocannon and the lane switching worked.

**Comment by ecomett** [comment]
I have a problem similar to this. It isn't switching lanes at all, it acts as if lane switching is manual and just stays in whatever lane I left it in and doesn't correct itself when I switch lanes. it does auto click but nothing else. I have put it in manually into both firefox and chrome and it is still doing the same thing. It was working fine yesterday but isn't today. I'm not sure what to do.

**Comment by kiradotee** [comment]
ecomett, for you I would suggest to look at the above comment asking if you've tried purchasing autocannon.
For ProfessorKaos64, autocannon helps when no switching happens at all. I have 10 autocannons and the lanes do switch, but sometimes, as described above, they will stick to the empty one even if I try to manually change it the script will return me to the empty one.

**Comment by ecomett** [comment]
It works now, thank you.

**Comment by wchill** [comment]
Merged autocannon fix, you no longer need to buy an autocannon.
