### ISSUE TITLE
Abilities keeps getting hidden

### ISSUE THREAD

**Issue by LUXIIUS** [wchill/steamSummerMinigame#51]
Most abilities keeps getting hidden, even when not fighting a boss.

**Comment by matirion** [comment]
This is probably the raining gold setting, by default its set to block the abilities when raining gold is active. At least, that's what I understood from glancing over the code.

**Comment by BuddhaBuddy1** [comment]
Probably caused by issue 36:
https://github.com/wchill/steamSummerMinigame/issues/36

**Comment by wchill** [comment]
No longer an issue.
