### ISSUE TITLE
Is there a way to reload a crashed chrome tab automatically ? 

### ISSUE THREAD

**Issue by iNilo** [wchill/steamSummerMinigame#52]
Chrome sometimes runs out of memory, I would love to get a way to auto reload the crashed tab.

**Comment by Eriner** [comment]
Use Easy-Auto-Refresh, set time to 1800 (30 minutes) and click 'Start'

https://chrome.google.com/webstore/detail/easy-auto-refresh/aabcgdmkeabbnleenpncegpcngjpnjkc?hl=en
