### ISSUE TITLE
Upgrading only one elemental damage is not optimal

### ISSUE THREAD

**Issue by Ferk** [wchill/steamSummerMinigame#54]
There's a much higher overall gain in damage per coin spent if the elemental damage upgrades are evenly distributed.

Assuming there are 2 enemies, one Fire and one Water, if you have level 3 fire and only level 1 water the total damage received will be 4x  (Fire Enemy:3x + Water Enemy:1x), but if you had level 2 fire and level 2 water instead, you will do 5x the damage (Fire Enemy:2.5x + Water Enemy:2.5x).

That's a significant difference (an extra time) that is more significant the more damage you do without the bonus and even more if you max out Fire and neglect all the other elements in comparison.

Why does the script by default hide all the elements except for one? if the point was to force you to optimize your damage per coin then it's doing it wrong.

**Comment by wchill** [comment]
it was for experimentation. Also your numbers are wrong, in the first case damage will be 5x as each level increases base by 1.5x (so 4x, 1x).

**Comment by BuddhaBuddy1** [comment]
They are basically even, but then you get no benefit from Max Elemental Damage, since they are all the same, whereas if you have one maxed, then you get a good benefit.
