### ISSUE TITLE
Priority wrong when 2 lanes have raining gold.

### ISSUE THREAD

**Issue by Klockwork** [wchill/steamSummerMinigame#55]
If a boss lane and a minion lane have raining gold, the priority went to the minion lane.

**Comment by Klockwork** [comment]
Possibly related: priority for raining gold auto target should be the highest health minion. Which it is not right now.

**Comment by Huntakillaz** [comment]
"If a boss lane and a minion lane have raining gold, the priority went to the minion lane."
Have seen this in v2.03 where it would switch to minion from boss.

**Comment by oedw** [comment]
See if you can use the latest version and report back

**Comment by oedw** [comment]
I don't know how feasible targeting the highest minion will be since if many people running the bot will target the higher minion, the non-targeted minion will become the higher health one (eventually). This will cause the bot to keep switching between minions, possibly diminishing the amount of gold gained

**Comment by Klockwork** [comment]
@oedw I misread the text for raining gold. I thought it was 1% of targets health per click, Though that does beg the question of what determines a monsters gold. I would assume the gold drop goes Boss>Treasure>mini boss>spawner>minions. Which I think the script is doing.

As to the original issue, I haven't seen that behavior in 3.x.x.

**Comment by oedw** [comment]
@Klockwork The script values/prioritizes Treasure over Boss, but otherwise you are correct.

If it has been fixed/finished, can you close the issue?
