### ISSUE TITLE
Autoclicking is broken

### ISSUE THREAD

**Issue by Eriner** [wchill/steamSummerMinigame#59]
Auto-clicking has been broken in the last few commits. I will take a look at the code and see what the problem is.

**Comment by Naosyth** [comment]
I just tried reverting to a much older version, and it still wasn't working. Possibly countered by Valve?

**Comment by Eriner** [comment]
This commit https://github.com/wchill/steamSummerMinigame/commit/a6af3ead541503119339945eb7786c279ce78d37 removed 'clickTheThing' and many other functions; improper merge.

**Comment by Huntakillaz** [comment]
Can confirm, reverted back to 2.03 to have it work again.

**Comment by wilflare** [comment]
reverted back to 2.03 as well (using Naosyth's link)
how did you guys even find that version :O

**Comment by Eriner** [comment]
commit https://github.com/wchill/steamSummerMinigame/commit/a6af3ead541503119339945eb7786c279ce78d37 was merged very poorly, and had a bunch of 'fix-it' commits following. I suggest forking, reverting, and trying again, and after it is confirmed working, commit to master. This is why you never make commits like that on the master.

**Comment by Huntakillaz** [comment]
I've had it since this morning. I'm glad i didn't overwrite it.

**Comment by oedw** [comment]
@Eriner It still "clicks" on line 190

```javascript
g_Minigame.m_CurrentScene.m_nClicks = currentClickRate;
```

**Comment by wchill** [comment]
@Eriner: I use the newer method. I will be reinserting the old method and an option to toggle for those that want it, but there is no real practical difference between the two other than this way is more efficient

**Comment by Eriner** [comment]
regardless, it is not auto-clicking since the merge, as far as I can tell.

**Comment by crimzonrayne** [comment]
+1 to auto-clicking not working post merge,

Using:
Google Chrome Version 44.0.2403.39 beta-m (64-bit)
TamperMonkey Version 3.10.109

**Comment by Eriner** [comment]
The issue isn't with it just missing 'clickTheThing', the problem is it was a dirty merge, and it what (as far as I can tell) what broke auto-clicking. This issue needs to be re-opened, as it has not been fixed.

**Comment by crimzonrayne** [comment]
@Eriner After some additional testing it looks like @wchill is correct, the key here is that the gold update happens server side since the DoClick method is what triggers the gold update on screen. A page refresh should update your gold. I've been seeing reports on the sub-reddit that there's still issues, but if @wchill is adding the toggle between the front end/back end methods then I think it's safe to leave this closed as long as good docs on how the new/old click methods work are generated.

**Comment by Eriner** [comment]
@crimzonrayne Yeah, I actually looked at the code instead of just the visual on the screen, my mistake.

**Comment by oedw** [comment]
autoclicking called the function ``` doClick() ``` which basically incremented ``` m_nClicks ``` alongside of adding flinching effects and the text

**Comment by Eriner** [comment]
right, it doesn't change anything server-side, only visuals (and efficiency) client-side. Should be documented in the Readme.md.

**Comment by crimzonrayne** [comment]
It is important to note that this effectively removes the purpose of "Remove particle effects" and "Remove flinching effects" which could add to the confusion. Possibly add an enhancement to not show these when using the server-side method?

**Comment by Eriner** [comment]
@crimzonrayne having them enabled still results in an increase in the memory leak. Documentation in the Readme is sufficient.

**Comment by Huntakillaz** [comment]
Ok so visually i think there needs to be a on/off toggle for some indication with the new method that it's working.

Running v2.03 & 3.70 side by side, it feels as if the 3.07 isn't doing the dps.
Also i can see the benefit of this mode as the 2.03 game's visual seems to be lagging behind a bit
