### ISSUE TITLE
Doesn't seem to switch to lowest health Spawner

### ISSUE THREAD

**Issue by BuddhaBuddy1** [wchill/steamSummerMinigame#61]
I saw that lane 3 had a low health spawner, but it wouldn't switch to it. I tried to switch to it, but of course, it switched me back to lane 2, which had a nearly full health spawner and three high-health spawn. It seems to switch OK when there is a low-health spawn, but not a low-health spawner.

**Comment by BuddhaBuddy1** [comment]
It may be that the monster element preference is overriding the lower damage (ie. I have extra water damage, and it may prefer to do extra damage over switching to a lower-health spawner).

**Comment by wchill** [comment]
Not sure if this is still valid. Closing for now.
