### ISSUE TITLE
Serverside Click Limit seems to have defeated clickrate.

### ISSUE THREAD

**Issue by y9yjRQcg7F** [wchill/steamSummerMinigame#79]
I have the click rate set to an impossibly high number and the crit, damage, and gold texts respond accordingly.  Despite this, enemies aren't dying any quicker and gold isn't actually earned anywhere near the rate shown with the damage text.

Should I just leave it at 10 at this point?

**Comment by Eriner** [comment]
server caps the cpm (at around 30 or 40, I believe?) so setting it higher than that is pointless, as all the damage and text you see is processed client-side, but any gold purchases you do are verified by the server. Lower the number to something reasonable and close this issue, please.

**Comment by Eriner** [comment]
cps, not cpm*

**Comment by y9yjRQcg7F** [comment]
Word - thanks for the input.  Closed.
