### ISSUE TITLE
Stack "Decrease Cooldowns" with 1h cooldown abilities

### ISSUE THREAD

**Issue by dunZgg** [wchill/steamSummerMinigame#82]
Right now the script is not using Decrease Cooldowns.

Wouldn't it make sense to stack it with Metal Detector, Nukes, Napalm, Cluster Bomb based on the current level to get those buffs every 45m?

**Comment by oedw** [comment]
+ we can also wait for a decrease cooldown to be present in the lane before calling one in since they don't stack. If one isn't present then we can call our own decrease cooldown

**Comment by wchill** [comment]
Referencing https://github.com/SteamDatabase/steamSummerMinigame/pull/208
