### ISSUE TITLE
[Suggestion] Integrate Auto-Refresher to prevent memory leak

### ISSUE THREAD

**Issue by wilflare** [wchill/steamSummerMinigame#93]
The reddit link dump suggests using an Auto-Refresher to circumvent the memory leak
http://www.reddit.com/r/SteamMonsterGame/comments/39ru4t/psalink_dump_for_the_game/

I'm personally not a fan of installing more extensions...
- any chance we can have auto-refresh integrated with just the .js?

**Comment by wchill** [comment]
It is actually included now if you are using Greasemonkey or Tampermonkey (or so I'm told). If you're using neither of those and copy pasting the script, then you should not auto-refresh as the script will be unloaded.

**Comment by wilflare** [comment]
I'm using Tampermonkey! I left the window on/active but it crashed (Ooops!) when I came back after dinner :/

**Comment by ryantheleach** [comment]
I've had it auto refresh successfully with tampermonkey.

**Comment by wilflare** [comment]
ehhh is there a setting or something I missed out?

**Comment by adrianmace** [comment]
My auto-refresh using Tampermonkey / Chrome does something odd. 

Refreshes correctly but gets stuck on 97/97 when reloading. Script is never restarted.

**Comment by masonelmore** [comment]
I saw the auto refresh with the script work. It would be nice to be able to set the interval and have a timer to make it easier to test.

**Comment by wchill** [comment]
A lot of people have been getting 97/97. I'll get someone on it.

**Comment by wchill** [comment]
Should be fixed by #161.
