### ISSUE TITLE
Steam logout

### ISSUE THREAD

**Issue by welwood08** [wchill/steamSummerMinigame#95]
I figure I should mention this in case anyone else has noticed it. My game was redirected to the main Steam login page twice in the last few hours. It could be something I've done at my end, but better not take any chances.

**Comment by wchill** [comment]
I have not had this issue. Did you tell Steam website to keep you logged in/remember you?

**Comment by welwood08** [comment]
Not sure, I don't usually use this particular browser for Steam so could be - surprised I hadn't encountered this until day 3 though. I'll wait for the game to finish, logout and see if I'm missing the checkbox.

**Comment by welwood08** [comment]
I had 3 more logouts but think I fixed it by manually allowing steamcommunity.com to set cookies for store.steampowered.com in uMatrix - makes sense, was just difficult to see it was happening because of the login page redirecting on submit. Hopefully anyone else in a similar situation finds this useful.
