### ISSUE TITLE
Powers of 2,

### ISSUE THREAD

**Issue by ryantheleach** [wchill/steamSummerMinigame#96]
Do you have any stats on what the game id's were for the past 3 days?

We noticed a massive jump in ID numbers, and todays main game id was 37 552

What's the chance that a new bit is being flipped on the high end for each day, seems awfully close to 32768 is all. Could predicting the next game id help us get a room full of scripters?

If the new ID for todays games are ~= 105063 it would look likely that this is the case.

**Comment by HeiZeus** [comment]
I don't remember Day 1, but this are the following reddit rooms that made it to the #1 spot:

Day 2: 6059
Day 3: 37559 
Day 4: 39650 almost there! :D
So I'm guessing its more of how many rooms are open per day. So maybe tomorrow they will be at around 45000's.

**Comment by ryantheleach** [comment]
Day 4 didn't line up with what I had going, so marking this as closed.
